code refactoring and script for train
uberkinder/Nometa-Bot pull request #11
Opened 2023-04-25 19:56 UTC by lzvsk

2023-04-26 06:28 UTC, w3ban requested changes
Вроде комментарии по всем файлам дал, из главного, я всё-таки настаиваю на метриках как отдельных сущностях. Получается мы все подгоняем под нашу задачу, а по-хорошему, чтобы каждый модуль мог существовать отдельно, по крайней мере я так вижу

2023-04-26 06:28 UTC, w3ban commented on src/utils/utils.py
>      Функция проверяет, является ли сообщение мета-вопросом.
имя функции лучше дать немного иначе, сейчас непонятно патерн чего мы чекаем
вот примеры названий

- check_is_meta_question
- сheck_question_pattern
Я за первый вариант, непонятно зачем удалять переменную templates, опять же теряется гибкость, если мы захотим передать другие pattern question, то надо лезть в переменную(а можно было просто другие вопросы подать на вход)

2023-04-26 06:28 UTC, w3ban commented on src/utils/utils.py
> +    TODO: add descrp
тоже странный нейминг, написано check_model(проверяем модель?), а в функции делаем предикт

- predict_with_tfidf
может что-то такое?

2023-04-26 06:28 UTC, w3ban commented on static/fit_predict_tfidf_classifier.py
> +from src.metrics import MetricsCalculator
Импорты в неправильном порядке, сначала third-party modules, потом сгруппированные импорты из модуля

2023-04-26 06:28 UTC, w3ban commented on static/fit_predict_tfidf_classifier.py
> +    X_train, X_test, y_train, y_test = train_test_split(
нет докстринга

2023-04-26 06:28 UTC, w3ban commented on static/fit_predict_tfidf_classifier.py
> +
Из-за того что у нас метрики в классе, просто лишнюю строчку добавляем в код

2023-04-26 06:28 UTC, w3ban commented on static/fit_predict_tfidf_classifier.py
> +
в логгер можно добавить отсечку из метрики, чтобы было понятно recall@spec N%

2023-04-26 06:28 UTC, w3ban commented on static/fit_predict_tfidf_classifier.py
> +    )
функция  check-tfidf-model делает то же самое

2023-04-26 06:28 UTC, w3ban commented on src/app/bot.py
> +message_check = checking_tfidf_model  # checking_tfidf_model, pattern_checking
может убрать эту функцию, сделать функцию подгрузки модели и просто в check_message делать предикт

2023-04-26 17:57 UTC, lzvsk commented on src/metrics/metrics.py
Собственно под это задел. Что бы сделать потом агрегирующую функцию по всем метрикам

2023-04-26 18:01 UTC, lzvsk commented on src/utils/utils.py
>      Функция проверяет, является ли сообщение мета-вопросом.
check_is_meta_question - внутри может находится любая проверка, описание все же лучше давать по смыслу функции. сheck_question_pattern - огонь, добавлю так. Переменную удаляем т.к. у нас эта функция уже встроена в бота - надо придерживаться однотипного входа, что бы быстро могли поменять 1 переменную и уже получать предикты не по модели, а по паттернам. В конечном итоге у нас останется все равно 1 решение

2023-04-26 18:03 UTC, lzvsk commented on src/utils/utils.py
> +    TODO: add descrp
Поправил с учетом единого стиля

2023-04-26 18:04 UTC, lzvsk commented on static/fit_predict_tfidf_classifier.py
> +
Таску на обобщенные метрики добавлю, сейчас пока не сильно критично. В идеале 1 строка вызова - вывод всех метрик

2023-04-26 18:05 UTC, lzvsk commented on static/fit_predict_tfidf_classifier.py
> +    )
Да, но тут у нас файл с примером. Если кто полезет внутрь, что бы понимал что происходит. Твое предложение по поводу нотбуков актуально же? Возможно этот скрипт просто в ноутбук засунем как пример

2023-04-26 18:08 UTC, lzvsk commented on src/app/bot.py
> +message_check = checking_tfidf_model  # checking_tfidf_model, pattern_checking
Временное решение пока будем тестить разные модели, можно быстро тут поменять тип предикта. По итогу это удалим и будет только 1 функция проверки сообщения

2023-04-26 18:08 UTC, lzvsk commented on static/fit_predict_tfidf_classifier.py
> +
Не совсем понял о какой отсечке?

2023-04-26 18:09 UTC, lzvsk commented on static/fit_predict_tfidf_classifier.py
> +    X_train, X_test, y_train, y_test = train_test_split(
умышленно не добавлял. Тут простые функции в которых 3 действия и говорящие названия. Возможно перетащим в ноутбук

2023-04-26 18:11 UTC, lzvsk commented on src/models/__init__.py
> +from models.tfidf_text_classifier.model import TfidfTextClassifier
спасибо, поправил

2023-04-26 18:11 UTC, lzvsk commented on README.md
>       * `metric/` - files for evaluating the quality of models
сделано

2023-04-26 18:13 UTC, lzvsk commented on src/models/__init__.py
> +from models.tfidf_text_classifier.model import TfidfTextClassifier
но тут собственно model.tfidf_text = .tfidf_text, так что без разницы было)

2023-04-26 18:26 UTC, w3ban commented on static/fit_predict_tfidf_classifier.py
> +    )
Отлично

2023-04-26 18:29 UTC, w3ban requested changes

2023-04-26 18:29 UTC, w3ban commented on src/utils/__init__.py
> +__all__ = ["сheck_question_pattern", "сheck_question_by_tfidf_model"]
Лучше сделать check_with_model звучит более человечно

2023-04-26 18:30 UTC, lzvsk commented on static/fit_predict_tfidf_classifier.py
> +
Понял, поправил

2023-04-26 18:31 UTC, lzvsk commented on src/utils/__init__.py
> +__all__ = ["сheck_question_pattern", "сheck_question_by_tfidf_model"]
model у нас разные могут быть, и разные функции которые будут эти предикты делать. Пока для явности предлагаю все же оставить

2023-04-26 18:33 UTC, lzvsk commented on src/metrics/metrics.py
Запилил агрегирующую функцию

2023-04-27 13:48 UTC, w3ban requested changes
Всё ок, я бы разве что название классу с метриками поменял и добавить надо predict_proba

2023-04-27 18:35 UTC, lzvsk commented on src/metrics/metrics.py
> +
+

2023-04-27 18:40 UTC, w3ban approved these changes

2023-04-27 18:58 UTC, w3ban approved these changes

2023-04-27 18:59 UTC, merged